language: python
os: linux
python: 3.7

jobs:
   include:
      - stage: build docker image
        script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t pedidos_backend . -f Dockerfile
        - docker images
        - docker tag pedidos_backend $DOCKER_USERNAME/pedidos_backend
        - docker push $DOCKER_USERNAME/pedidos_backend