version: '3'

volumes:
  db:


services:
  frontend:
    restart: always
    image: astandre/pedidos_frontend
    container_name: pedidos_frontend
    volumes:
      - .:/app_fe
    ports:
      - "4200:4200"
    depends_on:
      - backend


  backend:
    restart: always
    image: astandre/pedidos_backend
    container_name: pedidos_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app_be
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: pedidos_db
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

