version: '3'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=pedidos-staging
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=pedidosSystem.settings.staging
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db