# Generated by Django 3.0.4 on 2020-03-12 21:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarioHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=16, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'default_related_name': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=12)),
                ('calles', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
                'default_related_name': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=4)),
                ('mesa', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'default_related_name': 'mesas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(default=1)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('estado', models.CharField(choices=[('P', 'PREPARANDO'), ('L', 'PREPARADO'), ('C', 'COMPLETO'), ('G', 'PAGADO')], default='P', max_length=2)),
                ('tiempo_total', models.TimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidosHandler.Cliente')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidosHandler.Mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'default_related_name': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('especificacion', models.CharField(blank=True, max_length=200, null=True)),
                ('llevar', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidosHandler.Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventarioHandler.Producto')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'default_related_name': 'items',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='pedidosHandler.Direccion'),
        ),
    ]
