# Generated by Django 3.0.4 on 2020-03-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='mesa',
            field=models.CharField(max_length=40),
        ),
    ]
