# Generated by Django 2.1.7 on 2019-02-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosHandler', '0002_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('AI', 'Afuera puerta izquierda')], default='P', max_length=1),
        ),
    ]
