# Generated by Django 3.0.4 on 2020-03-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosHandler', '0002_auto_20200312_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='llevar',
            field=models.BooleanField(default=False),
        ),
    ]
