# Generated by Django 3.0.4 on 2020-04-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosHandler', '0003_pedido_llevar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tiempo_preparado',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tiempo_servido',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('P', 'PREPARANDO'), ('C', 'PREPARADO'), ('S', 'COMPLETO'), ('G', 'PAGADO')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
