# Generated by Django 3.0.5 on 2020-04-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosHandler', '0004_auto_20200403_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('P', 'PREPARANDO'), ('C', 'PREPARADO'), ('S', 'SERVIDO'), ('G', 'PAGADO')], default='P', max_length=2),
        ),
    ]
