# Generated by Django 2.1.7 on 2019-02-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosHandler', '0004_auto_20190219_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='especificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('P', 'PREPARANDO'), ('C', 'COMPLETO'), ('G', 'PAGADO')], default='P', max_length=1),
        ),
    ]
