# Generated by Django 3.0.4 on 2020-04-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosHandler', '0005_auto_20200417_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cocinado',
            field=models.BooleanField(default=False),
        ),
    ]
