# Generated by Django 2.1.7 on 2019-02-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosHandler', '0005_auto_20190219_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
