# Generated by Django 3.0.4 on 2020-04-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosHandler', '0007_auto_20200418_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(blank=True, default='COSUMIDOR FINAL', max_length=100),
        ),
    ]
