# Generated by Django 2.1.7 on 2019-03-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosHandler', '0007_auto_20190303_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tiempo_total',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
